[ADD] elico_crm_extra
Elico-Corp/odoo-8.0 pull request #122
Opened 2016-09-27 09:38 UTC by noahzaozao

@elicoidal @seb-elico This module is not installed in our ERP , move it to here.

2016-09-27 10:23 UTC, seb-elico requested changes

2016-09-27 10:23 UTC, seb-elico commented on elico_crm_extra/__init__.py
> +# -*- coding: utf-8 -*-
Can you use short headers please?

2016-09-27 10:23 UTC, seb-elico commented on elico_crm_extra/__openerp__.py
> +# -*- coding: utf-8 -*-
Can you use short headers please?

2016-09-27 10:23 UTC, seb-elico commented on elico_crm_extra/__openerp__.py
> +    'name': 'Elico CRM',
Let's rename it to `CRM period filters` (and the module name: `crm_period_filters`)
@elicoidal do you confirm? Should we keep this module in the first place?

2016-09-27 16:58 UTC, elicoidal commented
Seems very specific. I would keep it private Elico @seb-elico @victormartinelicocorp @noahzaozao

2016-10-12 09:24 UTC, seb-elico commented
@elicoidal it might be very specific but since we don't use it (not installed in our ERP), IMO we can leave it in our public addons to keep it somewhere

2016-10-12 09:24 UTC, noahzaozao commented
@elicoidal @seb-elico I moved this PR to https://github.com/Elico-Corp/elico_odoo/pull/51

2016-10-12 09:27 UTC, seb-elico commented
@noahzaozao based on my last comment, I'm reopening it and closing Elico-Corp/elico_odoo#51

2016-10-12 09:28 UTC, seb-elico commented
LGTM FT

2016-10-12 09:29 UTC, merged