[ADD] elico_project_extra
Elico-Corp/odoo-8.0 pull request #124
Opened 2016-09-27 10:13 UTC by noahzaozao

@seb-elico @elicoidal Please review this PR , this is from elico_odoo but not installed in our ERP.

2016-09-27 10:46 UTC, seb-elico commented
@noahzaozao @elicoidal this module is a mess, it has so many different purposes. Including some very Elico specific features (send an email to Eric for instance). I don't mind having it in our public addons (as long as we refactor it into several modules when we port it to v9) but we should remove the mentions to Elico related stuff

2016-09-27 10:48 UTC, seb-elico commented
Else we can keep it in `elico_odoo` but it's not even installed in our ERP :laughing:

2016-09-27 10:51 UTC, seb-elico requested changes

2016-09-27 10:51 UTC, seb-elico commented on elico_project_extra/__init__.py
> +##############################################################################
Short headers

2016-09-27 16:55 UTC, elicoidal commented
agree @seb-elico  this one is too messy to publish unless it is split. there is few interest in this effort.
We should have it in a repo private Elico

2016-10-12 09:26 UTC, seb-elico requested changes

2016-10-12 09:26 UTC, seb-elico commented on elico_project_extra/project.py
> +        email_from = "eric.caudal@elico-corp.com"
Please change to `admin@example.com`

2016-10-12 09:26 UTC, seb-elico commented on elico_project_extra/project.py
> +            email_cc = ["eric.caudal@elico-corp.com"]
Please change to `admin@example.com`

2016-10-12 09:26 UTC, seb-elico commented on elico_project_extra/__openerp__.py
> +    'name': 'Project Extra module for Elico Corp',
Please change to `Project Extra module`

2016-10-12 09:27 UTC, seb-elico commented
@elicoidal @noahzaozao IMO let's put it in our public repo and remove mentions to Elico Corp in the code (I requested some changes for that matter)

2016-10-12 09:32 UTC, noahzaozao commented
@seb-elico Done

2016-10-12 09:44 UTC, seb-elico commented
@noahzaozao sorry I forgot to ask, can you rename the module to `project_extra`?

2016-10-12 09:44 UTC, seb-elico approved these changes

2016-10-12 09:47 UTC, noahzaozao commented
@seb-elico Done

2016-10-12 10:52 UTC, seb-elico commented
LGTM FT

2016-10-12 10:52 UTC, merged