[ADD] server maintain
Elico-Corp/odoo-8.0 pull request #131
Opened 2016-10-24 04:09 UTC by noahzaozao

@elicoidal @seb-elico @xuan139 @victormartinelicocorp Please review and merge this PR.

2017-02-19 06:35 UTC, elicoidal requested changes
cleanse README/short headers/openerp.py and remove dead code.
It is not clear the name and usage of the module

2017-02-19 06:35 UTC, elicoidal commented on server_maintain/__init__.py
> +# -*- coding: utf-8 -*-
@noahzaozao Can you review this module?
remove/update commented code
Add a README and update short headers/openerp/.

2017-02-19 06:35 UTC, elicoidal commented on server_maintain/__init__.py
> +# -*- coding: utf-8 -*-
name of the module should be reviewed as well as it is not obvious to understand the meaning

2017-02-19 06:35 UTC, elicoidal commented on server_maintain/server.py
> +            [('postgres', 'Postgres'), ('openerp', 'OpenERP'),
s/openerp/Odoo

2017-02-19 06:35 UTC, elicoidal commented on server_maintain/server.py
> +        # 'oe_module_ids': fields.many2many(
remove dead code

2017-02-19 06:35 UTC, elicoidal commented on server_maintain/server_maintain.xml
> +                        <!-- <field name="oe_module_ids"  >
remove dead code

2017-02-19 06:35 UTC, elicoidal commented on server_maintain/server_oe_modules.py
> +    # _track = {
remove dead code

2017-08-02 05:31 UTC, elicoidal commented
@seb-elico @Zhouhao12345 do we stil need this code? Can we reuse part of it?
Otherwise, let's close this PR

2017-08-14 06:57 UTC, seb-elico commented
@elicoidal Not clear what is the purpose of that module. It looks like a monitoring tool but no idea why we created it (seems like Qiao Lei initiated the code) or if we simply forked/re-used the code of another customer/community project.

Anyway I don't really think this is re-usable but we can always merge it in our addons (once dead code is removed, short headers and Travis are fixed), same way we do for other "old" modules.

2017-08-14 07:15 UTC, elicoidal commented
OK: let's scrap it then

2017-08-14 07:15 UTC, closed without merging