move project_partner_name from project_partner_mandatory
Elico-Corp/odoo-8.0 pull request #133
Opened 2016-11-01 10:31 UTC by noahzaozao

2016-11-01 10:37 UTC, elicoidal requested changes
Check the current pending bugs

2016-11-01 10:37 UTC, elicoidal commented on project_partner_name/README.rst
> +* Modifies the name_search to search also by customer reference linked to project.
does it solve the 2 pending bugs:

* name_get of analytic account should be added as well
* when in task / project field: the name of the first customer is repeated in all lines

2016-11-01 10:37 UTC, elicoidal commented on project_partner_name/README.rst
> +Bugs are tracked on `GitHub Issues <https://github.com/Elico-Corp/elico_odoo/issues>`_.
update to latest OCA version

2016-11-01 10:37 UTC, elicoidal commented on project_partner_name/README.rst
> +* Victor M. Martin <victor.martin@elico-corp.com>
add Noah + Eric

2016-11-01 10:37 UTC, elicoidal commented on project_partner_name/README.rst
> +Elico Corporation offers consulting services to implement open source management software in SMEs, with a strong involvement in quality of service.
modify this footer with <80 char lines (and please inform everybody about the new footer)

2016-11-02 02:06 UTC, noahzaozao commented on project_partner_name/README.rst
> +* Modifies the name_search to search also by customer reference linked to project.
@elicoidal this PR is only move the module and rename it from elico_odoo , after it merged , Frank will work on these changes.

2016-11-02 02:11 UTC, noahzaozao commented on project_partner_name/README.rst
> +* Victor M. Martin <victor.martin@elico-corp.com>
@elicoidal added

2016-11-02 03:42 UTC, noahzaozao commented
@seb-elico @elicoidal Please review this pr thanks

2016-11-02 09:10 UTC, elicoidal requested changes
LGTM (small nitpick)

2016-11-02 09:10 UTC, elicoidal commented on project_partner_name/README.rst
> +project.
add 2 spaces at the beginning of the line
```
* Modifies the name_search to search also by customer reference linked to
  project
```

2016-11-03 03:42 UTC, noahzaozao commented
@seb-elico @elicoidal Please review this pr thanks

2016-11-03 06:36 UTC, xuan139 commented
LGTM

2016-11-03 06:37 UTC, merged

2016-11-04 07:51 UTC, elicoidal commented on project_partner_name/README.rst
> +  * Makes "Customer" mandatory field.
add a blank  line before list