8.0 project partner name
Elico-Corp/odoo-8.0 pull request #135
Opened 2016-11-08 08:15 UTC by franksongfeng

add _get_partner_ref(self, proj)  for  the class AnalyticAccount

2016-11-08 08:19 UTC, franksongfeng commented
@seb-elico @noahzaozao @elicoidal @victormartinelicocorp @xuan139 pls review

2016-11-08 08:56 UTC, noahzaozao requested changes

2016-11-08 08:56 UTC, noahzaozao commented on project_partner_name/models/analytic_account_id.py
> +
too much lines , remove this line

2016-11-08 08:56 UTC, noahzaozao commented on project_partner_name/models/analytic_account_id.py
> +
too much line , remove this line

2016-11-11 01:54 UTC, noahzaozao approved these changes

2016-11-11 01:55 UTC, noahzaozao commented on project_partner_name/models/analytic_account_id.py
> +        return res
Please add a line at end of the py file

2017-01-12 11:21 UTC, elicoidal commented
@franksongfeng please attend pending details.
other than that :+1:  (needs testing)

@seb-elico @noahzaozao @victormartinelicocorp @xuan139 pls review

2017-01-18 01:45 UTC, noahzaozao commented
LGTM

2017-01-18 01:56 UTC, xuan139 commented
LGTM

2017-01-18 06:07 UTC, merged