[FIX] fix pos_membership dependency on membership_account_balance
Elico-Corp/odoo-8.0 pull request #140
Opened 2017-01-09 09:46 UTC by franksongfeng

add the module membership_account_balance

2017-01-09 10:52 UTC, elicoidal requested changes
some light modifications to follow OCA format.
Not checked the code and not needed (module is working fine in production)

2017-01-09 10:52 UTC, elicoidal commented on membership_account_balance/README.rst
> +Membership Management - Member Account Balance
Please embed this into the standard README template

2017-01-09 10:52 UTC, elicoidal commented on membership_account_balance/__init__.py
> +# -*- coding: utf-8 -*-
Please remove and use standard short copyright notice
(date should be 2015)

2017-01-09 10:52 UTC, elicoidal commented on membership_account_balance/__openerp__.py
> + 'description': """
remove: redundant with README

2017-01-09 10:52 UTC, elicoidal commented on membership_account_balance/__openerp__.py
> + 'demo': [],
remove demo and test keys

2017-01-09 10:52 UTC, elicoidal commented on membership_account_balance/README.rst
> +* Alex Duan <alex.duan@elico-corp.com>
add my name and contact information

2017-01-11 02:15 UTC, franksongfeng commented on membership_account_balance/__openerp__.py
> + 'demo': [],
done.

2017-01-11 02:15 UTC, franksongfeng commented on membership_account_balance/__openerp__.py
> + 'description': """
done.

2017-01-11 02:15 UTC, franksongfeng commented on membership_account_balance/__init__.py
> +# -*- coding: utf-8 -*-
done.

2017-01-11 02:15 UTC, franksongfeng commented on membership_account_balance/README.rst
> +Membership Management - Member Account Balance
done.

2017-01-11 02:16 UTC, franksongfeng commented on membership_account_balance/README.rst
> +* Alex Duan <alex.duan@elico-corp.com>
done.

2017-01-11 02:19 UTC, victormartinelicocorp commented on membership_account_balance/__init__.py
> +# © 2015 Elico Corp (www.elico-corp.com).
@franksongfeng @elicoidal If we modify this information should we update the current year (2017)? . And the same for the changed headers.

2017-01-11 04:17 UTC, franksongfeng commented on membership_account_balance/__init__.py
> +# -*- coding: utf-8 -*-
@elicoidal travis has 2 main issues: The module membership_accont_balance has deprecated syntax, Would I change its code?; Other modules except membership_... has many warning/errors,  How to handle them?

2017-01-11 10:39 UTC, elicoidal commented on membership_account_balance/__init__.py
> +# -*- coding: utf-8 -*-
ignore warning (non blocking).
Deprecated syntax might not be a problem: check if this is blocking.

Anyway I fear the travis for the repo v8.0 might have many other issues.

2017-01-11 10:40 UTC, elicoidal commented
No keep 2015 which is the date we created the code and for which we can claim ownership

2017-01-12 11:23 UTC, elicoidal commented
@franksongfeng any improvement on this one?

2017-01-12 12:34 UTC, franksongfeng commented on membership_account_balance/__init__.py
> +# © 2015 Elico Corp (www.elico-corp.com).
the latest copyright year is needed to confirm by elico, @elicoidal, can we use 2017 as the latest year?

2017-01-12 13:40 UTC, elicoidal commented
2015 is the copyright year.
 




------------------
--
 	    Eric Caudal [Founder and CEO]
                              Skype: elico.corp. Phone: + 86 186 2136 1670 (Cell), + 86 21 6211 8017/27/37 (Office)             
             Elico Shanghai (Hong Kong/Shenzhen/Singapore)             
Odoo Gold Partner // Best Odoo Partner APAC 2014 and 2016
 

 
 
 
------------------ Original ------------------
From: "Frank Song (Elico)"; 
Date: Thursday, Jan 12, 2017 8:34 PM
To: "Elico-Corp/odoo-addons"; 
Cc: "Eric Caudal"; "Mention"; 
Subject: Re: [Elico-Corp/odoo-addons] [FIX] Fix pos_membership unmetdependency on membership_account_balance (#140)

 

@franksongfeng commented on this pull request.
 
 
In membership_account_balance/__init__.py:
 > -# -#    This program is free software: you can redistribute it and/or modify -#    it under the terms of the GNU Affero General Public License as -#    published by the Free Software Foundation, either version 3 of the -#    License, or (at your option) any later version. -# -#    This program is distributed in the hope that it will be useful, -#    but WITHOUT ANY WARRANTY; without even the implied warranty of -#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the -#    GNU Affero General Public License for more details. -# -#    You should have received a copy of the GNU Affero General Public License -#    along with this program.  If not, see <." target="_blank">http://www.gnu.org/licenses/>. -# -############################################################################## +# © 2015 Elico Corp (www.elico-corp.com).  
the latest copyright year is needed to confirm by elico, @elicoidal, can we use 2017 as the latest year?
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.

2017-01-22 03:09 UTC, seb-elico commented
> @franksongfeng any improvement on this one?

@elicoidal is there some more things that Frank needs to fix? Seems like all your previous comments have been addressed.

2017-01-22 03:23 UTC, franksongfeng commented
seb,
now my one PR (https://github.com/Elico-Corp/odoo-addons/pull/140)  is not merged, this can caused some modules  including pos_membership failed.  If any issue still existed after merging #140, that will be puzzled for me.
now my testbed including pr #140 work well.

--
Frank Song [Developer]
                  Skype: fowlersong. Phone:                   + 86 186 2155 9600 (Cell), + 86 21 6211 8017/27/37                   (Office) 
                 Elico Shanghai                   (Hong Kong/Shenzhen/Singapore) 
Odoo Gold Partner,                     best Odoo Partner 2016 for APAC 

 
 
 
------------------ Original ------------------
From:  "Sébastien Maillard - Elico Corp"<notifications@github.com>;
Date:  Sun, Jan 22, 2017 11:09 AM
To:  "Elico-Corp/odoo-addons"<odoo-addons@noreply.github.com>; 
Cc:  "Frank Song (Elico)"<frank.song@elico-corp.com>; "Mention"<mention@noreply.github.com>; 
Subject:  Re: [Elico-Corp/odoo-addons] [FIX] Fix pos_membership unmetdependency on membership_account_balance (#140)

 
 
@franksongfeng any improvement on this one?
  
@elicoidal is there some more things that Frank needs to fix? Seems like all your previous comments have been addressed.
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.

2017-01-23 02:26 UTC, elicoidal commented on membership_account_balance/README.rst
> +Membership Management - Member Account Balance
If I am not wrong this is not the standard README template

2017-01-23 02:30 UTC, elicoidal commented
This PR seems doesnot exit

2017-01-23 10:30 UTC, elicoidal commented on membership_account_balance/README.rst
> +Membership Management - Member Account Balance
@seb-elico @xuan139 Can you please male sure this is finished once and for all?

2017-02-10 07:04 UTC, seb-elico commented
@franksongfeng looks like a duplicate of #45, please make sure you avoid duplicates!
@noahzaozao IMO we should close this PR, please advise

2017-02-10 13:05 UTC, elicoidal commented
Closing for duplicated

2017-02-10 13:05 UTC, closed without merging