[WIP] business_requirement_deliverable_project_task_mandatory
Elico-Corp/odoo-8.0 pull request #159
Opened 2017-03-21 12:16 UTC by victormartinelicocorp

2017-03-22 06:22 UTC, victormartinelicocorp commented
@Elico-Corp/odoo-reviewers Please review and note in the PR name Task and BR

2017-03-22 06:26 UTC, victormartinelicocorp commented
Better work with updated version of:
OCA/project 8.0 regards PRs  https://github.com/OCA/project/pull/239 and https://github.com/OCA/project/pull/240

Need to have merge on `@noahzaozao BR repository` : PR https://github.com/OCA/business-requirement/pull/89

cc @Elico-Corp/odoo-reviewers

2017-03-22 06:53 UTC, elicoidal requested changes
some details, mostly English.
I would propose it to the OCA as well
About the name, what about business_requirement_task_mandatory

2017-03-22 06:53 UTC, elicoidal commented on business_requirement_deliverable_project_task_mandatory/README.rst
> +Business Requirement Project and allow to set a Category
allows

2017-03-22 06:53 UTC, elicoidal commented on business_requirement_deliverable_project_task_mandatory/README.rst
> +that will make required have all task linked to a Business Requirement.
that will make all tasks linked to a Business Requirement required.

2017-03-22 06:53 UTC, elicoidal commented on business_requirement_deliverable_project_task_mandatory/README.rst
> +#. Select one Category and check br_required
"BR Required"

2017-03-22 06:53 UTC, elicoidal commented on business_requirement_deliverable_project_task_mandatory/README.rst
> +Maintainer
I think this module could be added to the OCA

2017-03-22 06:53 UTC, elicoidal commented on business_requirement_deliverable_project_task_mandatory/models/project_project_category.py
> +        help='If marked as true the task linked to the project'
If marked as true the business requirement link in the task linked to this project will be mandatory

2017-03-22 06:53 UTC, elicoidal commented on business_requirement_deliverable_project_task_mandatory/models/project_task.py
> +# import json
remove dead code

2017-03-22 06:53 UTC, elicoidal commented on business_requirement_deliverable_project_task_mandatory/models/project_task.py
> +# © 2016 Elico Corp (www.elico-corp.com).
be consistent with the copyright

2017-03-22 06:53 UTC, elicoidal commented on business_requirement_deliverable_project_task_mandatory/models/project_task.py
> +                    'Project related category requires'
The Business Requirement is mandatory for this type of project category

2017-03-22 07:00 UTC, victormartinelicocorp commented
> some details, mostly English.
I would propose it to the OCA as well
About the name, what about business_requirement_task_mandatory

@elicoidal I think the name should reflect at least one the modules that depends on. So if check depends will see this name of module but I could change it if you want

2017-03-22 07:04 UTC, victormartinelicocorp commented on business_requirement_deliverable_project_task_mandatory/README.rst
> +Maintainer
Better later?
Actually our module for Project Category works fine and I rather avoid new migration.

The dependency is solved and is just a matter to improve later to converge with OCA/project modules and deprecate our `project_project_category`

2017-03-22 07:20 UTC, elicoidal commented
> I think the name should reflect at least one the modules that depends on. So if check depends will see this name of module but I could change it if you want

Agree: dont change the name.

2017-03-22 07:21 UTC, elicoidal commented on business_requirement_deliverable_project_task_mandatory/README.rst
> +Maintainer
Actually the project category doesnot work fine AFAIK and we should switch to the new one asap

2017-03-22 07:26 UTC, elicoidal approved these changes

2017-03-22 07:26 UTC, elicoidal commented
@noahzaozao @seb-elico @xuan139 please review

2017-03-30 05:21 UTC, victormartinelicocorp commented
> Better work with updated version of:
OCA/project 8.0 regards PRs OCA/project#239 and OCA/project#240
Need to have merge on @noahzaozao BR repository : PR OCA/business-requirement#89

All these PR are now merged. Could be merged this PR @Elico-Corp/odoo-reviewers?

2017-03-31 23:26 UTC, merged