[WIP] Port TMS report to new API
Elico-Corp/odoo-8.0 pull request #172
Opened 2017-07-26 12:04 UTC by seb-elico

2017-07-26 12:19 UTC, seb-elico commented
@victormartinelicocorp @Wizr @Zhouhao12345 can you answer the FIXMEs in my code please?

2017-07-27 01:18 UTC, elicoidal approved these changes
LGTM (no feedback on the new API questions though)

2017-07-27 01:18 UTC, elicoidal commented on timesheet_activity_report/__openerp__.py
> +    'version': '8.0.1.1.0', #FIXME is it the right version? I assume the module needs to be upgraded...
correct: restart+upgrade, no migration (https://github.com/OCA/maintainer-tools/blob/master/CONTRIBUTING.md#version-numbers)

2017-07-27 04:08 UTC, seb-elico commented on timesheet_activity_report/__openerp__.py
> +    'version': '8.0.1.1.0', #FIXME is it the right version? I assume the module needs to be upgraded...
@elicoidal Actually, so far the fields are the same, it's just a port to new API. So I'm wondering if an upgrade of the module is necessary!

2017-07-27 04:51 UTC, elicoidal commented on timesheet_activity_report/__openerp__.py
> +    'version': '8.0.1.1.0', #FIXME is it the right version? I assume the module needs to be upgraded...
It depends if you include the change in the SQL view or not in this PR.

2017-07-28 04:28 UTC, seb-elico commented on timesheet_activity_report/__openerp__.py
> +    'version': '8.0.1.1.0', #FIXME is it the right version? I assume the module needs to be upgraded...
Indeed I simplified the SQL view (not for the BR yet, I wanted to do that in a separate PR), you're right. Thanks!

2017-08-14 12:10 UTC, seb-elico commented
@Elico-Corp/odoo-reviewers Final version, please review

2017-08-15 01:17 UTC, elicoidal requested changes
some details. overall LGTM but needs to be tested

2017-08-15 01:17 UTC, elicoidal commented on timesheet_activity_report/README.rst
> +#. Have basic modules installed (hr_timesheet, project_timesheet, project_issue_sheet)
doesnot make sense to make an enumerated list with one item no?

2017-08-15 01:17 UTC, elicoidal commented on timesheet_activity_report/README.rst
> -Bugs are tracked on `GitHub Issues <https://github.com/Elico-Corp/odoo/issues>`_.
I miss the runbot

2017-08-15 01:17 UTC, elicoidal commented on timesheet_activity_report/report/timesheet_activity_report.py
> +             "Timesheets input directly")
Timesheet direct input

2017-08-15 02:42 UTC, seb-elico commented on timesheet_activity_report/README.rst
> +#. Have basic modules installed (hr_timesheet, project_timesheet, project_issue_sheet)
I just copy/pasted the README from another module that also had only 1 item. Any recommendation then?

2017-08-15 02:43 UTC, seb-elico commented on timesheet_activity_report/README.rst
> -Bugs are tracked on `GitHub Issues <https://github.com/Elico-Corp/odoo/issues>`_.
Project is not under Runbot

2017-08-15 02:45 UTC, seb-elico commented on timesheet_activity_report/report/timesheet_activity_report.py
> +             "Timesheets input directly")
@elicoidal Actually, the full sentence should be:

> "Type is used to separate Timesheets input in a Task, in an Issue or in Timesheet Activities" 

Is that ok for you?

2017-08-15 02:46 UTC, victormartinelicocorp commented on timesheet_activity_report/README.rst
> +#. Have basic modules installed (hr_timesheet, project_timesheet, project_issue_sheet)
IMO this looks cleaner:
```
Have basic modules installed:

   * hr_timesheet
   * project_timesheet
   * project_issue_sheet
```

2017-08-15 06:24 UTC, elicoidal requested changes
some nice to have details

2017-08-15 06:24 UTC, elicoidal commented on timesheet_activity_report/README.rst
> -Bugs are tracked on `GitHub Issues <https://github.com/Elico-Corp/odoo/issues>`_.
OK

2017-08-15 06:24 UTC, elicoidal commented on timesheet_activity_report/report/timesheet_activity_report.py
> +             "Timesheets input directly")
Another option (and name could be source or origin maybe but n-t-h)
Type is based on the origin of the input (Task, Issue or Timesheet Activity Report)

2017-08-15 08:01 UTC, seb-elico commented
@victormartinelicocorp Any idea why Travis is failing?

````
File "/home/travis/build/Elico-Corp/odoo-addons/timesheet_activity_report/report/timesheet_activity_report.py", line 121, in init
)""")
File "/home/travis/odoo-8.0/openerp/sql_db.py", line 171, in wrapper
return f(self, *args, **kwargs)
File "/home/travis/odoo-8.0/openerp/sql_db.py", line 247, in execute
res = self._obj.execute(query, params)
ProgrammingError: column p.business_requirement_id does not exist
LINE 58:                         ON b.id = p.business_requirement_id
````

2017-08-15 08:10 UTC, seb-elico commented
@victormartinelicocorp I found why it's failing, I just pushed a new `oca_dependencies.txt`. Let's see if it'll fix the bug

2017-08-15 08:22 UTC, seb-elico commented
@elicoidal @victormartinelicocorp can you approve please? Let's merge as soon as Travis build is green

2017-08-15 08:25 UTC, victor-ditay approved these changes

2017-08-15 10:45 UTC, elicoidal approved these changes

2017-08-15 10:45 UTC, merged