[MIG][10.0-Issue175-T23298] ldap_password
Elico-Corp/odoo-8.0 pull request #177
Opened 2017-08-25 07:41 UTC by sudhir-serpentcs

Migrated auth_ldap_self_signed in v10.
@elicoidal @seb-elico @victormartinelicocorp Please review.
This PR refers to issue #175

2017-08-25 07:50 UTC, elicoidal requested changes
some details on my side.
Not sure about the demo data and the tests here

2017-08-25 07:50 UTC, elicoidal commented on ldap_password/__init__.py
> +# © 2017 Elico corp (www.elico-corp.com)
2015-2017 (you need to keep the original date always)

2017-08-25 07:50 UTC, elicoidal commented on ldap_password/__manifest__.py
> +# © 2017 Elico corp (www.elico-corp.com)
2015-2017 Elico Corp (https://www.elico-corp.com)

(same everywhere)

2017-09-05 00:56 UTC, elicoidal approved these changes

2017-09-05 02:11 UTC, victor-ditay approved these changes
To be tested

2019-03-25 03:02 UTC, merged