[ADD] project_task_type_remaining_time_zero
Elico-Corp/odoo-8.0 pull request #193
Opened 2017-10-10 08:16 UTC by victormartinelicocorp

- Forgoten feature on refactoring elico_project

2017-10-10 08:16 UTC, victormartinelicocorp commented
@elicoidal @seb-elico Please have a check

2017-10-10 10:42 UTC, elicoidal approved these changes
LGTM

2017-10-10 10:42 UTC, elicoidal commented on project_task_type_remaining_time_zero/README.rst
> +<https://github.com/Elico-Corp/{project_repo}/issues>`_. In case of trouble, please
update

2017-10-10 10:42 UTC, elicoidal commented on project_task_type_remaining_time_zero/__init__.py
> +# © 2015-2017 Elico corp (https://www.elico-corp.com)
remove copyright in `__init__.py`

2017-10-11 03:28 UTC, victormartinelicocorp commented
@elicoidal

2017-10-11 07:14 UTC, elicoidal commented
Can you check travis?

2017-10-11 10:28 UTC, victormartinelicocorp commented
> Can you check travis?

```
109.77s$ travis_run_tests

======== Testing test_flake8 ========

project_completion_report/__openerp__.py:25:1: W391 blank line at end of file

project_completion_report/report/project_completion_report.py:45:9: E128 continuation line under-indented for visual indent

project_completion_report/report/project_completion_report.py:163:1: W391 blank line at end of file

======== Testing test_pylint ========

************* Module auth_cas.res_config

auth_cas/res_config.py:10: [W0403(relative-import), ] Relative import 'pycas', should be 'auth_cas.pycas'

From https://github.com/Elico-Corp/odoo-addons

 * [new branch]      8.0        -> origin/8.0
```

@elicoidal I fixed the errors regards this module, but basic all the other modules already on the master branch would fail.
Let fix on an specific PR as actually I can't know how many of them would fail

2017-10-11 11:37 UTC, elicoidal commented
I thought you already fixed the issue of pycas

2017-10-12 05:37 UTC, victormartinelicocorp commented
> I thought you already fixed the issue of pycas

@elicoidal I couldn't find time. Think now would finish it.

2017-10-12 06:05 UTC, victormartinelicocorp commented
> I thought you already fixed the issue of pycas

@elicoidal One thing is that I haven't spotted yet:

This would implies migrate to new API all modules pointed.
So is more than just small adjustment on Travis. Not a problem for me as far you know.

cc @seb-elico

2017-10-12 13:41 UTC, elicoidal commented
@victormartinelicocorp IMO no need for new API in v8 (not mandatory by Travis).
Fixing the pycas import should be good enough

2017-10-13 04:03 UTC, victormartinelicocorp commented
> @victormartinelicocorp IMO no need for new API in v8 (not mandatory by Travis).
Fixing the pycas import should be good enough

@elicoidal Weird that was pointed by Travis, I really didn't want to modify those modules but start to raise errors for the non CamelCase class, use of cr.commit(), old api osv deprecated and other like files should not have execution rights.

2017-10-16 07:33 UTC, seb-elico commented
@victormartinelicocorp This module has nothing to do with task **type**. It should be called `project_task_stage_remaining_time_zero`. Please refactor all references to `type`

2017-10-16 07:33 UTC, seb-elico requested changes
Refactor `type` to `stage`

2017-10-16 07:35 UTC, seb-elico commented
@victormartinelicocorp FYI Travis is failing for all the repo, not just your PR. I think it's better to create a separate PR to fix Travis, later this one will become green automatically (might require a re-build though)

2017-10-16 07:36 UTC, victormartinelicocorp commented
> Refactor type to stage

@seb-elico Odoo but internally is called `type` but agree the name is not so good so I will change it.

2017-10-16 07:39 UTC, victormartinelicocorp commented
> @victormartinelicocorp FYI Travis is failing for all the repo, not just your PR. I think it's better to create a separate PR to fix Travis, later this one will become green automatically (might require a re-build though)

@seb-elico Is what I did (#196) then I refactored this PR. Is still failing on which PR?

2017-10-16 07:46 UTC, seb-elico commented
> @seb-elico Odoo but internally is called type but agree the name is not so good so I will change it.

@victormartinelicocorp Well spotted! Indeed functional name is "Task Stage" and technical name is `project.task.type`.
@elicoidal Which name seems the best? Maybe call the module "Project Task Stage - Set remaining time to zero" and keep the technical name `project_task_type_remaining_time_zero`

> @seb-elico Is what I did (#196) then I refactored this PR. Is still failing on which PR?

Maybe you need to re-build this one now (simply add 1 commit)

2017-10-16 10:17 UTC, elicoidal commented
> Which name seems the best? Maybe call the module "Project Task Stage - Set remaining time to zero" and keep the technical name project_task_type_remaining_time_zero

What about: project_task_set_remaining_time_zero

2017-10-24 12:44 UTC, elicoidal commented
What are we waiting for?

2017-10-26 02:25 UTC, victormartinelicocorp commented
> What are we waiting for?

@seb-elico Could you check to approve it?

2019-03-25 03:17 UTC, merged