[ADD][BR1228][T24770]Extra time application
Elico-Corp/odoo-8.0 pull request #206
Opened 2017-12-14 10:58 UTC by Miya609

2017-12-15 07:58 UTC, elicoidal commented
Is it ready to be reviewed @Miya609 ?

2017-12-15 08:03 UTC, Miya609 commented
@Eric Caudal  not yet.I am make test more perfect.

 
------------------ Original ------------------
From:  "Eric @ Elico Corp"<notifications@github.com>;
Date:  Fri, Dec 15, 2017 03:58 PM
To:  "Elico-Corp/odoo-addons"<odoo-addons@noreply.github.com>; 
Cc:  "Miya Xing-Elico corp"<miya.xing@elico-corp.com>; "Mention"<mention@noreply.github.com>; 
Subject:  Re: [Elico-Corp/odoo-addons] [ADD][BR1228][T24770]Extra timeapplication (#206)

 

Is it ready to be reviewed @Miya609 ?
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.

2017-12-18 08:10 UTC, lonelysun requested changes
please fix

2017-12-18 08:10 UTC, lonelysun commented on extra_time_application/__manifest__.py
> +    'version': '10.0.1.0.0',
why version is  '10.0.1.0.0'?

2017-12-18 08:10 UTC, lonelysun commented on extra_time_application/models/project_task_inherit.py
> +        remaining = self.remaining_hours
adapt api.multi

2017-12-18 08:10 UTC, lonelysun commented on extra_time_application/models/project_task_inherit.py
> +            if not vals.get('project_id.is_modified'):
what't this?

2017-12-18 08:10 UTC, lonelysun commented on extra_time_application/models/task_timesheet.py
> +    task_no = fields.Many2one('project.task', 'Task No', help='Task No')
m2o field should be named xxx_id

2017-12-19 01:29 UTC, elicoidal requested changes
Too many simple mistakes

2017-12-19 01:29 UTC, elicoidal commented on extra_time_application/LICENSE
> +Elico Proprietary License v1.0
No need this file. This module can be AGPLv3

2017-12-19 01:29 UTC, elicoidal commented on extra_time_application/README.rst
> +
add the other contributors (Eric, Sebastien, Hulk)

2017-12-19 01:29 UTC, elicoidal commented on extra_time_application/__manifest__.py
> +    'version': '10.0.0.0.0',
Actually @lonelysun 10.0.1.0.0 should be the correct start (first version of the module in v10)

2017-12-19 01:29 UTC, elicoidal commented on extra_time_application/__manifest__.py
> +    'license': 'Other proprietary',
You are not being logical/consistent: here it says proprietary but everywhere you say AGPL!
license should be AGPLv3

2017-12-19 01:29 UTC, elicoidal commented on extra_time_application/models/project_task_inherit.py
> +                        'reason': 'Automaticity create From PM or Reviewer',
Automatically created from PM or Reviewer

2017-12-19 01:29 UTC, elicoidal commented on extra_time_application/models/project_task_inherit.py
> +                            'The task have no enough time, '
'The task has no enough time left, '

2017-12-19 01:29 UTC, elicoidal commented on extra_time_application/models/project_task_inherit.py
> +                            'please Apply for more extra time'
add a period at the end of the sentence

2017-12-19 01:29 UTC, elicoidal commented on extra_time_application/models/project_task_inherit.py
> +                    _('You do not have permission'))
to do what?

2017-12-19 01:29 UTC, elicoidal commented on extra_time_application/models/project_task_inherit.py
> +                'name': _('Extra Time Approve'),
Approve->Approval

2017-12-19 01:29 UTC, elicoidal commented on extra_time_application/models/task_timesheet.py
> +        ('to_approve', 'To Approve'),
No need for `draft` state?

2017-12-19 01:29 UTC, elicoidal commented on extra_time_application/tests/test_extra_time.py
> +class TestExtraTime(common.TransactionCase):
you are not testing anything here, just covering the percentage.
For example, you need to test approval by user -> should fail

2017-12-19 01:29 UTC, elicoidal commented on extra_time_application/tests/test_extra_time.py
> +            'reason': 'Automaticity create From PM or Reviewer',
Automatically created

2017-12-19 01:29 UTC, elicoidal commented on extra_time_application/tests/test_extra_time_wizard.py
> +# Elico Proprietary License v1.0.
license is AGPL (everywhere)

2017-12-19 01:29 UTC, elicoidal commented on extra_time_application/tests/test_project_task_save.py
> +        except Exception:
I am surprised: should not this trigger an error so that the test fails?

2017-12-19 01:29 UTC, elicoidal commented on extra_time_application/tests/test_project_task_save.py
> +                'date_time': '2017-12-15',
For all date, I would suggest to use today() and relative dates in the future today()+2 for example

2017-12-19 01:29 UTC, elicoidal commented on extra_time_application/wizard/extra_time_application_wizard.py
> +        is_exist = user.has_group(
Improve the variable name

2017-12-19 01:29 UTC, elicoidal commented on extra_time_application/wizard/extra_time_application_wizard.py
> +                'reason': 'Automaticity create From PM or Reviewer',
Automatically created from

2017-12-19 09:15 UTC, Miya609 commented
@elicoidal No need for draft state,and I fix other error,could you review it?

2017-12-19 09:25 UTC, elicoidal commented
Travis still failing it seems

2017-12-19 09:27 UTC, elicoidal commented on extra_time_application/models/project_project_inherit.py
> +    is_modified = fields.Boolean()
What is this for?
This column is never assigned and has no title.
What is the usage?
cc @lonelysun

2017-12-20 02:45 UTC, Miya609 commented
@elicoidal Please review it.

2017-12-20 04:21 UTC, elicoidal commented
Travis is still failing 
@Miya609 @lonelysun

2017-12-20 04:23 UTC, lonelysun commented
I’m finding the reason now.

Hulk Liu [Developer]
Phone: +86 186 1691 1517 (Cell), +86 21 6211 8017/27/37 (Office) 
Elico Shanghai (Hong Kong/Shenzhen/Singapore) <http://www.elico-corp.com/>
Odoo Gold Partner // Best Odoo Partner APAC 2014 and 2016 


Sent by Shanghai Elico Limited - 上海寰享网络科技有限公司 <http://www.elico-corp.com/> using Odoo <https://www.odoo.com/> about Timesheet Week 47 <https://www.elico-corp.com/web?db=elico_stable#action=mail.action_mail_redirect&login=hulk.liu%40elico-corp.com&message_id=417889>

2018-01-12 09:02 UTC, Miya609 commented
@seb-elico Could you tell me the reason that why the travis not working?

2018-03-21 04:04 UTC, lonelysun commented
move to #210

2018-03-21 04:04 UTC, closed without merging