[ADD] auth_cas 9.0 ver.
Elico-Corp/odoo-8.0 pull request #233
Opened 2019-02-12 03:46 UTC by etoanik

add auth_cas 9.0 version from 10.0

2019-02-12 09:52 UTC, elicoidal commented
@etoanik Thanks for the contribution!
Let me get somebody to review it so that we can merge it soon.
@JoJoJoJoJoJoJo @joycehuan @victormartinelicocorp

2019-02-13 06:10 UTC, elicoidal requested changes
LGTM. Not tested (did you?)

2019-02-13 06:10 UTC, elicoidal commented on auth_cas/__openerp__.py
> +# © 2016-2018 Elico Corp (https://www.elico-corp.com).
2016-2019 (everywhere)

2019-02-13 06:15 UTC, etoanik commented
I had install in my odoo 9.0 env.

2019-02-20 02:19 UTC, victor-ditay requested changes

2019-02-20 02:19 UTC, victormartinelicocorp commented on auth_cas/controllers/main.py
> +from ..pycas import login
We should not have `pycas` as an embed library, we should add a fixed and stable version pip install on Travis and add this as external dependency named on __opernerp__.py

See OCA guidelines https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#17external-dependencies

See project https://pypi.org/project/pycas/

See an example https://github.com/OCA/reporting-engine/blob/11.0/report_xlsx/__manifest__.py#L16

2019-02-25 23:39 UTC, elicoidal commented
I will merge for the time being. Later on we will remove the dependency
Thanks for the contribution!

2019-03-25 03:24 UTC, merged

2019-03-25 03:24 UTC, elicoidal commented
@etoanik Thanks for the contribution!