[IMP]add module auth_signup_error_message.
Elico-Corp/odoo-8.0 pull request #33
Opened 2015-11-20 03:07 UTC by Rona111

2017-02-19 05:52 UTC, elicoidal requested changes
small details

2017-02-19 05:52 UTC, elicoidal commented on auth_signup_error_message/controllers/main.py
> +                    qcontext['error'] = _(u'两次填写的密码不一致，请重新填写密码')
English please

2017-02-19 05:52 UTC, elicoidal commented on auth_signup_error_message/controllers/main.py
> +                    qcontext['error'] = _(u'该用户名已经被注册，请重新填写用户名')
idem

2017-02-28 03:21 UTC, noahzaozao commented
@Elico-Corp/odoo-reviewers Please review this PR again , fixed small details above.

2017-03-01 01:29 UTC, noahzaozao commented
@elicoidal @seb-elico @victormartinelicocorp @xuan139

2017-03-01 01:30 UTC, merged