[IMP]add module web_login
Elico-Corp/odoo-8.0 pull request #35
Opened 2015-11-20 04:18 UTC by Rona111

2015-12-14 08:34 UTC, Rona111 commented
cc @elicoidal @duanyp1991 @siyuancn @seb-elico

2015-12-14 10:49 UTC, elicoidal commented on web_login/README.rst
> +This module extends the functionality of website to redirect to the main of the website when log in.
to the main menu?

2015-12-14 10:50 UTC, elicoidal commented on web_login/README.rst
> +Website Login
Redirect to shop after login

2015-12-14 10:51 UTC, elicoidal commented
module name: website_redirect_to_shop

2015-12-15 08:27 UTC, Rona111 commented
cc @elicoidal @seb-elico @duanyp1991 @siyuancn

2015-12-15 08:29 UTC, elicoidal commented
LGTM. To be tested in v9 (probably works as well)

2017-02-19 05:54 UTC, elicoidal requested changes
small changes in README

2017-02-19 05:54 UTC, elicoidal commented on website_redirect_to_shop/README.rst
> +Bugs are tracked on `GitHub Issues <https://github.com/Elico-Corp/odoo/issues>`_.
Adapt

2017-02-19 05:54 UTC, elicoidal commented on website_redirect_to_shop/README.rst
> +`here <https://github.com/Elico-Corp/odoo/issues/new?body=module:%20web_login%0Aversion:%20{8.0}%0A%0A**Steps%20to%20reproduce**%0A-%20...%0A%0A**Current%20behavior**%0A%0A**Expected%20behavior**>`_.
remove this line

2017-02-19 05:54 UTC, elicoidal commented on website_redirect_to_shop/README.rst
> +For further information, please visit:
remove this text and add Runbot

2017-02-19 05:54 UTC, elicoidal commented on website_redirect_to_shop/README.rst
> +Installation
remove following 2 sections

2017-02-19 05:54 UTC, elicoidal commented on website_redirect_to_shop/README.rst
> +This module is maintained by Elico Corporation.
update to newest template

2017-03-02 06:23 UTC, noahzaozao commented on website_redirect_to_shop/README.rst
> +This module is maintained by Elico Corporation.
done

2017-03-02 06:24 UTC, noahzaozao commented
@elicoidal please review again

2017-03-02 07:01 UTC, elicoidal approved these changes

2017-03-02 07:01 UTC, merged