[IMP]10697 add module website_forum_nutrition
Elico-Corp/odoo-8.0 pull request #36
Opened 2015-11-20 06:06 UTC by Rona111

2015-12-14 09:44 UTC, Rona111 commented
cc @elicoidal @seb-elico @duanyp1991 @siyuancn

2015-12-14 10:47 UTC, elicoidal commented on website_forum_nutrition/controllers/main.py
> +            values['forum'] = request.registry['forum.forum'].browse(request.cr, request.uid, kwargs.pop('forum_id'), context=request.context)
pep8?

2015-12-14 10:47 UTC, elicoidal commented on website_forum_nutrition/controllers/main.py
> +    @http.route(['/<model("forum.forum"):forum>/<model("product.symptom"):symptom>/products',
PEP8

2015-12-14 10:49 UTC, elicoidal commented
no unit test but I think this is OK.
Other than that small details

2015-12-15 08:08 UTC, Rona111 commented
cc @elicoidal @seb-elico @duanyp1991 @siyuancn

2015-12-15 08:11 UTC, elicoidal commented
LGTM, no technical tests. Isnot it duplicated with some I have seen days ago?

2015-12-16 08:52 UTC, Rona111 commented
@elicoidal  isnot it duplicated with some I have seen days ago? what do you mean?you mean no technical tests is ok or not?

2015-12-16 10:34 UTC, elicoidal commented
This PR is similar to another one I have reviewed days ago.
not important though

2017-02-19 05:56 UTC, elicoidal requested changes
update the README

2017-02-19 05:56 UTC, elicoidal commented on website_forum_nutrition/README.rst
> +Bugs are tracked on `GitHub Issues <https://github.com/Elico-Corp/odoo/issues>`_.
modify link

2017-02-19 05:56 UTC, elicoidal commented on website_forum_nutrition/README.rst
> +`here <https://github.com/Elico-Corp/odoo/issues/new?body=module:%20website_forum_nutrition%0Aversion:%20{8.0}%0A%0A**Steps%20to%20reproduce**%0A-%20...%0A%0A**Current%20behavior**%0A%0A**Expected%20
remove this line

2017-02-19 05:56 UTC, elicoidal commented on website_forum_nutrition/README.rst
> +This module is maintained by Elico Corporation.
use newest template

2017-03-02 06:26 UTC, noahzaozao commented on website_forum_nutrition/README.rst
> +This module is maintained by Elico Corporation.
done

2017-03-02 06:26 UTC, noahzaozao commented
@elicoidal please review this pr again

2017-03-02 07:00 UTC, elicoidal approved these changes

2017-03-02 07:00 UTC, merged