[IMP]10698 add module website_sales_order_and_reservation_process
Elico-Corp/odoo-8.0 pull request #37
Opened 2015-11-20 06:06 UTC by Rona111

2015-12-14 10:36 UTC, Rona111 commented
cc @elicoidal @seb-elico @duanyp1991 @siyuancn

2015-12-14 10:54 UTC, elicoidal commented on website_sales_order_and_reservation_process/__openerp__.py
> +        'website_sale_collapse_categories',
Is it really necessary to have those 2 dependencies?

2015-12-14 10:55 UTC, elicoidal commented on website_sales_order_and_reservation_process/views/templates_inherit.xml
> +                    购买产品可以当日发出，预定产品当日不能发出，
Avoid Chinese in the code

2015-12-14 10:56 UTC, elicoidal commented
It is not clear the purpose of this module (to be added in the README).
Besides it mixes different concepts to be removed (for example the copyright removal)

2015-12-14 10:57 UTC, elicoidal commented on website_sales_order_and_reservation_process/views/templates_inherit.xml
> +        <template id="remove_odoo_information" inherit_id="theme_loftspace.change_footer_copyright">
to be removed

2015-12-15 10:11 UTC, Rona111 commented on website_sales_order_and_reservation_process/__openerp__.py
> +        'website_sale_collapse_categories',
@elicoidal   because of this module still need a lot of fix.so I  just go ahead another module.

2015-12-15 10:15 UTC, siyuancn commented on website_sales_order_and_reservation_process/__openerp__.py
> +        'website_sale_collapse_categories',
@elicoidal some modification is base on this two dependencies. It's a special module for the jingma project. 
@Rona111 I thinks you need some extra time to remove these 2 dependencies, and modify the module for just depends on website_sale.

2015-12-15 10:20 UTC, Rona111 commented on website_sales_order_and_reservation_process/__openerp__.py
> +        'website_sale_collapse_categories',
@elicoidal  @siyuancn  I will push another modules first ,and do this module's migration after.

2015-12-15 11:01 UTC, elicoidal commented on website_sales_order_and_reservation_process/__openerp__.py
> +        'website_sale_collapse_categories',
OK. No need to lose time for that I think. Or we publish as is or we just cancel (my preferred option actually)

2017-02-19 05:58 UTC, elicoidal requested changes
Most problem: remove all Chinese +README

2017-02-19 05:58 UTC, elicoidal commented on website_sales_order_and_reservation_process/README.rst
> + * Disable the "Add to cart" button and show button "预定"
remove chinese

2017-02-19 05:58 UTC, elicoidal commented on website_sales_order_and_reservation_process/README.rst
> +Bugs are tracked on `GitHub Issues <https://github.com/Elico-Corp/odoo/issues>`_.
update

2017-02-19 05:58 UTC, elicoidal commented on website_sales_order_and_reservation_process/README.rst
> +Elico Corporation offers consulting services to implement open source management software in SMEs, with a strong involvement in quality of service.
newest template

2017-02-19 05:58 UTC, elicoidal commented on website_sales_order_and_reservation_process/static/src/js/website_sale_inherit.js
> +                    inventory_dom.val("购买").html("购买");
Remove chinese => use English and translation file

2017-02-19 05:58 UTC, elicoidal commented on website_sales_order_and_reservation_process/views/templates_inherit.xml
> +                        <div class="js_inventory" t-att-data-line-id="line.id" style="color:green">购买</div>
remove all Chinese

2017-03-02 06:28 UTC, noahzaozao commented
@elicoidal please review this pr again

2017-03-02 06:56 UTC, elicoidal requested changes
small details.
waiting for travis then merge

2017-03-02 06:56 UTC, elicoidal commented on website_sales_order_and_reservation_process/README.rst
> + * remove the string "Taxes" in shopping cart and payment
add empty line

2017-03-02 06:56 UTC, elicoidal commented on website_sales_order_and_reservation_process/README.rst
> + * total
same here

2017-03-02 07:23 UTC, merged