[IMP]10701 add module hr_payroll_report_horizontal_xls
Elico-Corp/odoo-8.0 pull request #40
Opened 2015-11-20 06:27 UTC by Rona111

2017-02-19 06:03 UTC, elicoidal requested changes
push this module to OCA/l10n-china

2017-02-19 06:03 UTC, elicoidal commented on hr_payroll_report_horizontal_xls/README.rst
> +Bugs are tracked on `GitHub Issues <https://github.com/Elico-Corp/odoo/issues>`_.
Update the URL and use newest template

2017-02-19 06:03 UTC, elicoidal commented on hr_payroll_report_horizontal_xls/README.rst
> +Elico Corporation offers consulting services to implement open source management software in SMEs, with a strong involvement in quality of service.
newest template

2017-02-19 06:03 UTC, elicoidal commented on hr_payroll_report_horizontal_xls/report_hr_payroll.py
> +import xlwt
Should protect the import

2017-03-02 06:32 UTC, noahzaozao commented
@elicoidal please review this pr again

2017-03-02 06:59 UTC, elicoidal commented
LGTM but travis is failing. is it related?

2017-03-02 07:25 UTC, noahzaozao commented
@elicoidal I'll fix it then merge it

2017-03-02 07:39 UTC, merged