[IMP]10703 add module mrp_production_workcenter_line_reporting_excel
Elico-Corp/odoo-8.0 pull request #42
Opened 2015-11-20 06:31 UTC by Rona111

2015-12-16 09:46 UTC, Rona111 commented
cc @elicoidal @seb-elico @siyuancn @duanyp1991

2015-12-16 10:28 UTC, elicoidal commented on mrp_production_workcenter_line_reporting_excel/README.rst
> +Excel report for Mrp Production
Mrp => MRP

2015-12-16 10:28 UTC, elicoidal commented on mrp_production_workcenter_line_reporting_excel/README.rst
> +
add a screenshot

2015-12-16 10:29 UTC, elicoidal commented on mrp_production_workcenter_line_reporting_excel/report/report_quantity.py
> +        main_title = u"协邦铸业产品工序产量报告ریخته گری دولت گزارش تولید گام محصول"
Switch to English

2015-12-16 10:30 UTC, elicoidal commented on mrp_production_workcenter_line_reporting_excel/report/report_scraped.py
> +        协邦铸业生产工序报废报告انجمن صنعت ریخته گری فرآیندهای تولید دولت قراضه گزارش"
English

2015-12-16 10:30 UTC, elicoidal commented on mrp_production_workcenter_line_reporting_excel/wizard/report_quantity.py
> +        select_statement = """
This statement doesnot seem multicompany

2015-12-16 10:31 UTC, elicoidal commented on mrp_production_workcenter_line_reporting_excel/wizard/report_quantity.py
> +            u'0': u"销售订单سفارش فروش",
English

2015-12-16 10:31 UTC, elicoidal commented on mrp_production_workcenter_line_reporting_excel/wizard/report_scraped.py
> +            u'0': u"销售订单سفارش فروش",
English

2015-12-17 01:26 UTC, siyuancn commented on mrp_production_workcenter_line_reporting_excel/wizard/report_quantity.py
> +        select_statement = """
There is a where statement below: where_statement = 'where mo.company_id = u.company_id' which check the company id.

2015-12-17 01:27 UTC, elicoidal commented on mrp_production_workcenter_line_reporting_excel/wizard/report_quantity.py
> +        select_statement = """
@siyuancn you are right! I overlooked it

2017-02-19 06:05 UTC, elicoidal requested changes
mostly README+Change Chinese/Farsi to English

2017-02-19 06:05 UTC, elicoidal commented on mrp_production_workcenter_line_reporting_excel/README.rst
> +Bugs are tracked on `GitHub Issues <https://github.com/Elico-Corp/odoo/issues>`_.
URL+newest template

2017-03-02 06:40 UTC, noahzaozao commented on mrp_production_workcenter_line_reporting_excel/README.rst
> +
where is the screenshot?

2017-03-02 06:48 UTC, noahzaozao commented
@elicoidal please review this pr again

2017-03-02 06:58 UTC, elicoidal commented on mrp_production_workcenter_line_reporting_excel/README.rst
> +
should be taken ;)
Forget about it

2017-03-02 06:58 UTC, elicoidal commented
travis needs some love? @noahzaozao

2017-03-02 07:59 UTC, noahzaozao commented
@elicoidal this module was depend on another module https://github.com/Elico-Corp/odoo-addons/pull/41

2017-03-03 03:31 UTC, merged