[IMP]10708 add module mass_items
Elico-Corp/odoo-8.0 pull request #46
Opened 2015-11-23 04:00 UTC by Rona111

2015-11-23 06:37 UTC, elicoidal commented on mass_items/__init__.py
> +# -*- coding: utf-8 -*-
Headers + README
Propose to the OCA
Change the name: product_mass_selection?

2015-11-23 06:38 UTC, elicoidal commented on mass_items/__init__.py
> +# -*- coding: utf-8 -*-
In theory you should have one module for sales, one for purchase, one for SM

2015-11-23 06:38 UTC, elicoidal commented on mass_items/__init__.py
> +# -*- coding: utf-8 -*-
then sale_mass_selection, purchase_mass_selection, stock_mass_selection

2017-02-19 06:07 UTC, elicoidal requested changes
mostly README

2017-02-19 06:07 UTC, elicoidal commented on mass_items/README.rst
> +'description': """
Use newest README template

2017-03-02 08:17 UTC, noahzaozao commented
@elicoidal please review this pr again

2017-03-02 09:17 UTC, elicoidal commented
Change the name of the module to mass_item_selection then merge

2017-03-03 08:56 UTC, merged