[IMP]10719 add module invoice_report.
Elico-Corp/odoo-8.0 pull request #56
Opened 2015-11-23 08:39 UTC by Rona111

2015-11-23 08:52 UTC, elicoidal commented on invoice_report/__openerp__.py
> +        Module which hides the OpenERP announcement bar.
? description is folkloric...

2015-11-23 08:54 UTC, elicoidal commented on invoice_report/__init__.py
> +import invoice_report
Header/README/PEP8

2015-12-22 10:28 UTC, Rona111 commented
cc @elicoidal @siyuancn @duanyp1991 @seb-elico

2015-12-23 00:15 UTC, elicoidal commented on invoice_report/README.rst
> +'description': """
@Rona111 What is this?
You need to check the modules first, not only copy paste.
README is completely wrong.

2015-12-23 00:17 UTC, elicoidal commented
What is the purpose of the module?
Create a new invoice report?
@duanyp1991 @siyuancn @seb-elico should we move forward or cancel?

2015-12-23 01:53 UTC, siyuancn commented on invoice_report/__openerp__.py
> +    'version': '1.0',
version is wrong

2015-12-23 01:54 UTC, siyuancn commented on invoice_report/company_view.xml
> +		<record id="company_form_detail_extend" model="ir.ui.view">
view id is: view_company_form

2015-12-23 01:55 UTC, siyuancn commented on invoice_report/invoice_report.py
> +    discount_amount = fields.Float(
Compute Field: the compute method pattern is _compute_<field_name>

2015-12-23 01:56 UTC, siyuancn commented on invoice_report/invoice_report.py
> +        string='Original Amount', compute='_original_amount')
Compute Field: the compute method pattern is \_compute_\<field_name\>

2015-12-23 01:58 UTC, siyuancn commented
@Rona111 Please make sure the purpose of the module first.

2017-02-19 06:10 UTC, elicoidal commented on invoice_report/README.rst
> +'description': """
Update to newest template

2017-02-19 06:10 UTC, elicoidal requested changes
Update template/short headers/openerp.py

2017-03-02 09:18 UTC, noahzaozao commented
@elicoidal please review this pr again

2017-03-02 10:18 UTC, elicoidal approved these changes

2017-03-02 10:18 UTC, merged