[IMP]10721 add module check_product_qty_with_material.
Elico-Corp/odoo-8.0 pull request #58
Opened 2015-11-23 08:49 UTC by Rona111

2015-11-23 13:04 UTC, elicoidal commented
To be cleansed (some Chinese in menu etc. no translation).
README/Header

2016-06-04 12:31 UTC, elicoidal commented
@rona111 this one is easy to fix: the Chinese menu mainly

2016-06-14 01:21 UTC, elicoidal commented on check_product_qty_with_material/wizard/check_product_qty_wizard.py
> +    def praepare_report(self, bom_map):
s/praepare/prepare

2016-06-14 01:21 UTC, elicoidal commented on check_product_qty_with_material/wizard/check_product_qty_wizard.py
> +    @api.one
obsolete

2016-06-14 01:21 UTC, elicoidal commented on check_product_qty_with_material/wizard/check_product_qty_wizard.py
> +    product_name = fields.Char(string='产品')
chinese

2016-06-14 01:23 UTC, elicoidal commented on check_product_qty_with_material/wizard/check_product_qty_wizard.xml
> +                <form string="计算产品可生产数量" version="7">
version is 7 or 8?

2016-06-14 01:24 UTC, elicoidal commented on check_product_qty_with_material/README.rst
> +This module extends the functionality of ... to support ...
not sure what this module do: prepare a description and I will correct it.

module name: product_bom_qty_check

2017-03-03 05:54 UTC, noahzaozao commented
@elicoidal please review this pr again

2017-03-03 07:56 UTC, elicoidal requested changes
some details to be fixed. Could be done by Kevin

2017-03-03 07:56 UTC, elicoidal commented on check_product_qty_with_material/product.py
> +    product_qty = fields.Float(string='Number of material')
Qty of Raw materials

2017-03-03 07:56 UTC, elicoidal commented on check_product_qty_with_material/product.py
> +    stock_qty = fields.Float(string='Number of stock')
Stock Qty

2017-03-03 07:56 UTC, elicoidal commented on check_product_qty_with_material/product.py
> +    can_product_qty = fields.Float(string='Number can be produced')
Qty that can be produced

2017-03-03 07:56 UTC, elicoidal commented on check_product_qty_with_material/product.py
> +    diff_qty = fields.Float(string='Number of differences')
Difference qty

2017-03-03 07:56 UTC, elicoidal commented on check_product_qty_with_material/README.rst
> +This module extends the functionality of ... to support ...
Reports to display the quantity of finished good that can be produced based on the quantity on stock of the raw materials.

2017-03-03 07:56 UTC, elicoidal commented on check_product_qty_with_material/README.rst
> +Installation
remove this section

2017-03-03 07:56 UTC, elicoidal commented on check_product_qty_with_material/README.rst
> +`here <https://github.com/Elico-Corp/odoo/issues/new?body=module:%20check_product_qty_with_material%0Aversion:%20{8.0}%0A%0A**Steps%20to%20reproduce**%0A-%20...%0A%0A**Current%20behavior**%0A%0A**Exp
remove this line

2017-03-03 07:56 UTC, elicoidal commented on check_product_qty_with_material/wizard/check_product_qty_wizard.xml
> +        <act_window name="计算产品可生产数量" res_model="check.product.qty.wizard" view_mode="form" target="new" id="action_check_product_qty_wizard"/>
remove Chinese

2017-03-06 10:05 UTC, noahzaozao commented
@elicoidal please review this pr again

2017-03-07 02:02 UTC, elicoidal approved these changes

2017-03-07 02:03 UTC, merged