[IMP]10731 add module sale_order_lines_discount.
Elico-Corp/odoo-8.0 pull request #67
Opened 2015-11-23 09:51 UTC by Rona111

2015-11-23 12:52 UTC, elicoidal commented
Sounds interesting module but copied from somewhere else.
Header/README/OpenERP/PEP8

2016-06-16 07:39 UTC, littleQ-zzq commented
cc @elicoidal @duanyp1991 @seb-elico @siyuancn

2016-06-16 07:44 UTC, duanyp1991 commented on sale_order_lines_discount/sale_order_lines.py
> +            if all_discounts < 100 and all_discounts >= 0:
discount cannot be 100 ?

2016-06-16 07:44 UTC, duanyp1991 commented on sale_order_lines_discount/sale_order_view.xml
> +        <record id="view_order_enterprise_form" model="ir.ui.view">
keep the xmlid the same as the inherited view. ref: oca guideline

2016-06-16 07:45 UTC, duanyp1991 commented on sale_order_lines_discount/sale_order_lines.py
> +        elp='Change all order lines discount.')
s/elp/help

2016-06-16 07:46 UTC, duanyp1991 commented on sale_order_lines_discount/sale_order_lines.py
> +        elp='Change all order lines discount.')
粗心

2016-06-16 07:46 UTC, seb-elico commented on sale_order_lines_discount/README.rst
> +Installation
Missing an empty line here, no?

2016-06-16 07:46 UTC, duanyp1991 commented on sale_order_lines_discount/sale_order_view.xml
> +                        <field name="all_discounts"/><button
button 换行

2016-06-16 07:49 UTC, duanyp1991 commented on sale_order_lines_discount/sale_order_lines.py
> +                    _("""Your discount value is out of vlaues,
s/vlaues/values, make a better warning message.

2016-06-16 07:49 UTC, seb-elico commented on sale_order_lines_discount/sale_order_view.xml
> +                    <xpath
Follow OCA XML format recommendations: https://github.com/OCA/maintainer-tools/blob/master/template/module/views/assets.xml

2016-06-16 07:49 UTC, seb-elico commented on sale_order_lines_discount/sale_order_view.xml
> +                               context="{'all_discounts':all_discounts}" />
Miss ` ` after `:`

2016-06-16 07:50 UTC, seb-elico commented on sale_order_lines_discount/sale_order_lines.py
> +            if all_discounts < 100 and all_discounts >= 0:
According to error message below, no. But functionally it might make sense

2016-06-16 07:50 UTC, duanyp1991 commented on sale_order_lines_discount/sale_order_lines.py
> +class SaleOrder(models.Model):
这个文件里面都是关于model `sale.order`的， 为什么名字叫：sale_order_lines.py, 有误导性。

2016-06-16 07:51 UTC, duanyp1991 commented on sale_order_lines_discount/sale_order_lines.py
> +        required=True,
required=True, 是不是应该给个default value?

2016-06-16 07:53 UTC, littleQ-zzq commented on sale_order_lines_discount/sale_order_lines.py
> +            if all_discounts < 100 and all_discounts >= 0:
In fact,I also don't know why,but the code befor exist wrote like this... and I don't know if it is the need of BR or not.

2016-06-16 07:56 UTC, littleQ-zzq commented on sale_order_lines_discount/sale_order_lines.py
> +            if all_discounts < 100 and all_discounts >= 0:
Yes, because it  exsit as a  percentage in the code.

2016-06-16 09:13 UTC, littleQ-zzq commented
cc @seb-elico  @duanyp1991

2017-02-19 06:16 UTC, elicoidal requested changes
Some updates

2017-02-19 06:16 UTC, elicoidal commented on sale_order_lines_discount/README.rst
> +`here <https://github.com/Elico-Corp/odoo-addons/issues/new?body=module:%20sale_order_lines.py%0Aversion:%20{8.0}%0A%0A**Steps%20to%20reproduce**%0A-%20...%0A%0A**Current%20behavior**%0A%0A**Expected
updte the README to newest template

2017-02-19 06:16 UTC, elicoidal commented on sale_order_lines_discount/sale_order.py
> +                        it's value between 0 and 100,but 100 except."""))
Value between 0 and less than 100.

2017-03-03 05:53 UTC, noahzaozao commented
@elicoidal please review this pr again

2017-03-03 07:52 UTC, elicoidal commented
Please attend comment then merge

2017-03-07 06:39 UTC, merged